FROM registry.redhat.io/rhel8/httpd-24

USER 0
ADD helloworld.php /var/www/html

RUN mkdir /tmp/src && chown -R 1001:0 /tmp/src
USER 1001

# Let the assemble script install the dependencies
RUN /usr/libexec/s2i/assemble

# The run script uses standard ways to run the application
CMD /usr/libexec/s2i/run