apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kirom-template
  annotations:
    openshift.io/display-name: Quotes Application
    description: The Quotes application provides an HTTP API that returns a random, funny quote.
    iconClass: icon-php
    tags: php,mysql
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: hellodb
    name: hellodb
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: hellodb
      deploymentconfig: hellodb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        labels:
          app: hellodb
          deploymentconfig: hellodb
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: sampledb
          - name: MYSQL_PASSWORD
            value: pass
          - name: MYSQL_USER
            value: user
          - name: MYSQL_ROOT_PASSWORD
            value: root
          imagePullPolicy: IfNotPresent
          name: hellodb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: hellodb-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: hellodb-volume-1
          persistentVolumeClaim:
            claimName: hellodb-claim
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hellodb
        from:
          kind: ImageStreamTag
          name: mysql:5.7
          # namespace: openshift
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: hellodb
    name: hellodb
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: hellodb
      deploymentconfig: hellodb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
    name: hellodb-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 300Mi
    storageClassName: standard
    volumeMode: Filesystem