kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "hello" 
  labels:
    app: hello
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "GitHub"
      github:
        secret: "secret101"
    - type: "Generic"
      generic:
        secret: "secret101"
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/tsrana/spring-boot-hello-world"
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "ubi8-openjdk-8:1.3"
        namespace: openshift
#  strategy:
#    type: Docker
#    dockerStrategy:
#      dockerfilePath: Dockerfile    
  output: 
    to:
      kind: "ImageStreamTag"
      name: "hello:latest"
